### ISSUE TITLE
CodeMagic - Shorebird - iOS Issue

### ISSUE THREAD

**Issue by mfurkanyuceal** [nilsreichardt/codemagic-shorebird-demo#2]
Hi, I want to release my ios app with shorebird codemagic action. But I got an error on Step Name => 🙌 Shorebird Build.
Previously, I could get release without using shorebird.

Error=>

![image](https://github.com/nilsreichardt/codemagic-shorebird-demo/assets/22933926/bf0d158f-20fd-48bb-8f65-63823013aaa7)
 
iOS Workflow =>

`
workflows:
  ios-shorebird-workflow:
    instance_type: mac_mini_m1
    name: iOS ShoreBird Workflow
    environment:
      ios_signing:
        provisioning_profiles:
          - For CodeMagic
        certificates:
          - Code Magic Certificate
      flutter: 3.10.6
      cocoapods: 1.13.0
      xcode: 15.0
      groups:
        - shorebird
        - appstore

    triggering:
      events:
        - tag

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    integrations:
      app_store_connect: "IOS Codemagic Integration"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

    artifacts:
      - build/ios/ipa/*.ipa

    scripts:
      - name: 🐦 Setup Shorebird
        script: |
          # Install Shorebird
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          
          # Add Shorebird to PATH
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV

      - name: Shorebird flutter versions set to 3.10.6
        script: |
          shorebird flutter versions use 3.10.6

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Flutter Packages Get and Translations
        script: |
          flutter pub get
          flutter packages pub global activate intl_utils
          flutter --no-color pub global run intl_utils:generate

      - name: Pods Install
        script: |
          rm -rf ios/Podfile.lock
          pod install --repo-update --project-directory=./ios

      - name: 🙌 Shorebird Build
        script: |
          echo "➡️ Using tag: $CM_TAG"
          
          # Check type and run corresponding command
          if [ "$TYPE" == *"#"* ]; then
            echo "🩹 Running patch command"
            shorebird patch ios-alpha --force
          else
            echo "🚀 Running release command"
            shorebird release ios-alpha --force
          fi
`

**Comment by ndasim** [comment]
Same here
